from pyactor.context import set_context, create_host, sleep, shutdown
from Peer import *
from Tracker import *

if __name__ == "__main__":
   set_context()
   h = create_host()

   tracker = h.spawn("tracker1", Tracker)
   peer0 = h.spawn("peer0", Peer)
   peer1 = h.spawn("peer1", Peer)
   peer2 = h.spawn("peer2", Peer)
   peer3 = h.spawn("peer3", Peer)
   peer4 = h.spawn("peer4", Peer)
   peer5 = h.spawn("peer5", Peer)
   peer6 = h.spawn("peer6", Peer)
   peer7 = h.spawn("peer7", Peer)
   peer8 = h.spawn("peer8", Peer)
   peer9 = h.spawn("peer9", Peer)
   peer10 = h.spawn("peer10", Peer)
   peer11 = h.spawn("peer11", Peer)
   peer12 = h.spawn("peer12", Peer)
   peer13 = h.spawn("peer13", Peer)
   peer14 = h.spawn("peer14", Peer)
   peer15 = h.spawn("peer15", Peer)
   peer16 = h.spawn("peer16", Peer)
   peer17 = h.spawn("peer17", Peer)
   peer18 = h.spawn("peer18", Peer)
   peer19 = h.spawn("peer19", Peer)
   peer20 = h.spawn("peer20", Peer)
   peer21 = h.spawn("peer21", Peer)
   peer22 = h.spawn("peer22", Peer)
   peer23 = h.spawn("peer23", Peer)
   peer24 = h.spawn("peer24", Peer)
   peer25 = h.spawn("peer25", Peer)
   peer26 = h.spawn("peer26", Peer)
   peer27 = h.spawn("peer27", Peer)
   peer28 = h.spawn("peer28", Peer)
   peer29 = h.spawn("peer29", Peer)
   peer30 = h.spawn("peer30", Peer)
   peer31 = h.spawn("peer31", Peer)
   peer32 = h.spawn("peer32", Peer)
   peer33 = h.spawn("peer33", Peer)
   peer34 = h.spawn("peer34", Peer)
   peer35 = h.spawn("peer35", Peer)
   peer36 = h.spawn("peer36", Peer)
   peer37 = h.spawn("peer37", Peer)
   peer38 = h.spawn("peer38", Peer)
   peer39 = h.spawn("peer39", Peer)
   peer40 = h.spawn("peer40", Peer)
   peer41 = h.spawn("peer41", Peer)
   peer42 = h.spawn("peer42", Peer)
   peer43 = h.spawn("peer43", Peer)
   peer44 = h.spawn("peer44", Peer)
   peer45 = h.spawn("peer45", Peer)
   peer46 = h.spawn("peer46", Peer)
   peer47 = h.spawn("peer47", Peer)
   peer48 = h.spawn("peer48", Peer)
   peer49 = h.spawn("peer49", Peer)

   modo = str(raw_input("por favor indique si desea usar push, pull o push-pull: "))
   peer0.set_mode(modo)
   peer1.set_mode(modo)
   peer2.set_mode(modo)
   peer3.set_mode(modo)
   peer4.set_mode(modo)
   peer5.set_mode(modo)
   peer6.set_mode(modo)
   peer7.set_mode(modo)
   peer8.set_mode(modo)
   peer9.set_mode(modo)
   peer10.set_mode(modo)
   peer11.set_mode(modo)
   peer12.set_mode(modo)
   peer13.set_mode(modo)
   peer14.set_mode(modo)
   peer15.set_mode(modo)
   peer16.set_mode(modo)
   peer17.set_mode(modo)
   peer18.set_mode(modo)
   peer19.set_mode(modo)
   peer20.set_mode(modo)
   peer21.set_mode(modo)
   peer22.set_mode(modo)
   peer23.set_mode(modo)
   peer24.set_mode(modo)
   peer25.set_mode(modo)
   peer26.set_mode(modo)
   peer27.set_mode(modo)
   peer28.set_mode(modo)
   peer29.set_mode(modo)
   peer30.set_mode(modo)
   peer31.set_mode(modo)
   peer32.set_mode(modo)
   peer33.set_mode(modo)
   peer34.set_mode(modo)
   peer35.set_mode(modo)
   peer36.set_mode(modo)
   peer37.set_mode(modo)
   peer38.set_mode(modo)
   peer39.set_mode(modo)
   peer40.set_mode(modo)
   peer41.set_mode(modo)
   peer42.set_mode(modo)
   peer43.set_mode(modo)
   peer44.set_mode(modo)
   peer45.set_mode(modo)
   peer46.set_mode(modo)
   peer47.set_mode(modo)
   peer48.set_mode(modo)
   peer49.set_mode(modo)

   peer0.attach_tracker(tracker)
   peer1.attach_tracker(tracker)
   peer2.attach_tracker(tracker)
   peer3.attach_tracker(tracker)
   peer4.attach_tracker(tracker)
   peer5.attach_tracker(tracker)
   peer6.attach_tracker(tracker)
   peer7.attach_tracker(tracker)
   peer8.attach_tracker(tracker)
   peer9.attach_tracker(tracker)
   peer10.attach_tracker(tracker)
   peer11.attach_tracker(tracker)
   peer12.attach_tracker(tracker)
   peer13.attach_tracker(tracker)
   peer14.attach_tracker(tracker)
   peer15.attach_tracker(tracker)
   peer16.attach_tracker(tracker)
   peer17.attach_tracker(tracker)
   peer18.attach_tracker(tracker)
   peer19.attach_tracker(tracker)
   peer20.attach_tracker(tracker)
   peer21.attach_tracker(tracker)
   peer22.attach_tracker(tracker)
   peer23.attach_tracker(tracker)
   peer24.attach_tracker(tracker)
   peer25.attach_tracker(tracker)
   peer26.attach_tracker(tracker)
   peer27.attach_tracker(tracker)
   peer28.attach_tracker(tracker)
   peer29.attach_tracker(tracker)
   peer30.attach_tracker(tracker)
   peer31.attach_tracker(tracker)
   peer32.attach_tracker(tracker)
   peer33.attach_tracker(tracker)
   peer34.attach_tracker(tracker)
   peer35.attach_tracker(tracker)
   peer36.attach_tracker(tracker)
   peer37.attach_tracker(tracker)
   peer38.attach_tracker(tracker)
   peer39.attach_tracker(tracker)
   peer40.attach_tracker(tracker)
   peer41.attach_tracker(tracker)
   peer42.attach_tracker(tracker)
   peer43.attach_tracker(tracker)
   peer44.attach_tracker(tracker)
   peer45.attach_tracker(tracker)
   peer46.attach_tracker(tracker)
   peer47.attach_tracker(tracker)
   peer48.attach_tracker(tracker)
   peer49.attach_tracker(tracker)

   peer0.set_file("1a")
   peer1.set_file("1a")
   peer2.set_file("1a")
   peer3.set_file("1a")
   peer4.set_file("1a")
   peer5.set_file("1a")
   peer6.set_file("1a")
   peer7.set_file("1a")
   peer8.set_file("1a")
   peer9.set_file("1a")
   peer10.set_file("1a")
   peer11.set_file("1a")
   peer12.set_file("1a")
   peer13.set_file("1a")
   peer14.set_file("1a")
   peer15.set_file("1a")
   peer16.set_file("1a")
   peer17.set_file("1a")
   peer18.set_file("1a")
   peer19.set_file("1a")
   peer20.set_file("1a")
   peer21.set_file("1a")
   peer22.set_file("1a")
   peer23.set_file("1a")
   peer24.set_file("1a")
   peer25.set_file("1a")
   peer26.set_file("1a")
   peer27.set_file("1a")
   peer28.set_file("1a")
   peer29.set_file("1a")
   peer30.set_file("1a")
   peer31.set_file("1a")
   peer32.set_file("1a")
   peer33.set_file("1a")
   peer34.set_file("1a")
   peer35.set_file("1a")
   peer36.set_file("1a")
   peer37.set_file("1a")
   peer38.set_file("1a")
   peer39.set_file("1a")
   peer40.set_file("1a")
   peer41.set_file("1a")
   peer42.set_file("1a")
   peer43.set_file("1a")
   peer44.set_file("1a")
   peer45.set_file("1a")
   peer46.set_file("1a")
   peer47.set_file("1a")
   peer48.set_file("1a")
   peer49.set_file("1a")

   f = open("chunksFile", "r").read()

   for i in range (0,f.__len__()):
      peer0.add_chunk(i, f[i])

   peer0.set_size(f.__len__())
   peer1.set_size(f.__len__())
   peer2.set_size(f.__len__())
   peer3.set_size(f.__len__())
   peer4.set_size(f.__len__())
   peer5.set_size(f.__len__())
   peer6.set_size(f.__len__())
   peer7.set_size(f.__len__())
   peer8.set_size(f.__len__())
   peer9.set_size(f.__len__())
   peer10.set_size(f.__len__())
   peer11.set_size(f.__len__())
   peer12.set_size(f.__len__())
   peer13.set_size(f.__len__())
   peer14.set_size(f.__len__())
   peer15.set_size(f.__len__())
   peer16.set_size(f.__len__())
   peer17.set_size(f.__len__())
   peer18.set_size(f.__len__())
   peer19.set_size(f.__len__())
   peer20.set_size(f.__len__())
   peer21.set_size(f.__len__())
   peer22.set_size(f.__len__())
   peer23.set_size(f.__len__())
   peer24.set_size(f.__len__())
   peer25.set_size(f.__len__())
   peer26.set_size(f.__len__())
   peer27.set_size(f.__len__())
   peer28.set_size(f.__len__())
   peer29.set_size(f.__len__())
   peer30.set_size(f.__len__())
   peer31.set_size(f.__len__())
   peer32.set_size(f.__len__())
   peer33.set_size(f.__len__())
   peer34.set_size(f.__len__())
   peer35.set_size(f.__len__())
   peer36.set_size(f.__len__())
   peer37.set_size(f.__len__())
   peer38.set_size(f.__len__())
   peer39.set_size(f.__len__())
   peer40.set_size(f.__len__())
   peer41.set_size(f.__len__())
   peer42.set_size(f.__len__())
   peer43.set_size(f.__len__())
   peer44.set_size(f.__len__())
   peer45.set_size(f.__len__())
   peer46.set_size(f.__len__())
   peer47.set_size(f.__len__())
   peer48.set_size(f.__len__())
   peer49.set_size(f.__len__())

   tracker.announce("1a","peer0")
   tracker.announce("1a","peer1")
   tracker.announce("1a","peer2")
   tracker.announce("1a","peer3")
   tracker.announce("1a","peer4")
   tracker.announce("1a","peer5")
   tracker.announce("1a","peer6")
   tracker.announce("1a","peer7")
   tracker.announce("1a","peer8")
   tracker.announce("1a","peer9")
   tracker.announce("1a","peer10")
   tracker.announce("1a","peer11")
   tracker.announce("1a","peer12")
   tracker.announce("1a","peer13")
   tracker.announce("1a","peer14")
   tracker.announce("1a","peer15")
   tracker.announce("1a","peer16")
   tracker.announce("1a","peer17")
   tracker.announce("1a","peer18")
   tracker.announce("1a","peer19")
   tracker.announce("1a","peer20")
   tracker.announce("1a","peer21")
   tracker.announce("1a","peer22")
   tracker.announce("1a","peer23")
   tracker.announce("1a","peer24")
   tracker.announce("1a","peer25")
   tracker.announce("1a","peer26")
   tracker.announce("1a","peer27")
   tracker.announce("1a","peer28")
   tracker.announce("1a","peer29")
   tracker.announce("1a","peer30")
   tracker.announce("1a","peer31")
   tracker.announce("1a","peer32")
   tracker.announce("1a","peer33")
   tracker.announce("1a","peer34")
   tracker.announce("1a","peer35")
   tracker.announce("1a","peer36")
   tracker.announce("1a","peer37")
   tracker.announce("1a","peer38")
   tracker.announce("1a","peer39")
   tracker.announce("1a","peer40")
   tracker.announce("1a","peer41")
   tracker.announce("1a","peer42")
   tracker.announce("1a","peer43")
   tracker.announce("1a","peer44")
   tracker.announce("1a","peer45")
   tracker.announce("1a","peer46")
   tracker.announce("1a","peer47")
   tracker.announce("1a","peer48")
   tracker.announce("1a","peer49")

   peer0.init_gossip_cycle()
   peer1.init_gossip_cycle()
   peer2.init_gossip_cycle()
   peer3.init_gossip_cycle()
   peer4.init_gossip_cycle()
   peer5.init_gossip_cycle()
   peer6.init_gossip_cycle()
   peer7.init_gossip_cycle()
   peer8.init_gossip_cycle()
   peer9.init_gossip_cycle()
   peer10.init_gossip_cycle()
   peer11.init_gossip_cycle()
   peer12.init_gossip_cycle()
   peer13.init_gossip_cycle()
   peer14.init_gossip_cycle()
   peer15.init_gossip_cycle()
   peer16.init_gossip_cycle()
   peer17.init_gossip_cycle()
   peer18.init_gossip_cycle()
   peer19.init_gossip_cycle()
   peer20.init_gossip_cycle()
   peer21.init_gossip_cycle()
   peer22.init_gossip_cycle()
   peer23.init_gossip_cycle()
   peer24.init_gossip_cycle()
   peer25.init_gossip_cycle()
   peer26.init_gossip_cycle()
   peer27.init_gossip_cycle()
   peer28.init_gossip_cycle()
   peer29.init_gossip_cycle()
   peer30.init_gossip_cycle()
   peer31.init_gossip_cycle()
   peer32.init_gossip_cycle()
   peer33.init_gossip_cycle()
   peer34.init_gossip_cycle()
   peer35.init_gossip_cycle()
   peer36.init_gossip_cycle()
   peer37.init_gossip_cycle()
   peer38.init_gossip_cycle()
   peer39.init_gossip_cycle()
   peer40.init_gossip_cycle()
   peer41.init_gossip_cycle()
   peer42.init_gossip_cycle()
   peer43.init_gossip_cycle()
   peer44.init_gossip_cycle()
   peer45.init_gossip_cycle()
   peer46.init_gossip_cycle()
   peer47.init_gossip_cycle()
   peer48.init_gossip_cycle()
   peer49.init_gossip_cycle()

   sleep(10)

   peer0.stop_interval()
   peer1.stop_interval()
   peer2.stop_interval()
   peer3.stop_interval()
   peer4.stop_interval()
   peer5.stop_interval()
   peer6.stop_interval()
   peer7.stop_interval()
   peer8.stop_interval()
   peer9.stop_interval()
   peer10.stop_interval()
   peer11.stop_interval()
   peer12.stop_interval()
   peer13.stop_interval()
   peer14.stop_interval()
   peer15.stop_interval()
   peer16.stop_interval()
   peer17.stop_interval()
   peer18.stop_interval()
   peer19.stop_interval()
   peer20.stop_interval()
   peer21.stop_interval()
   peer22.stop_interval()
   peer23.stop_interval()
   peer24.stop_interval()
   peer25.stop_interval()
   peer26.stop_interval()
   peer27.stop_interval()
   peer28.stop_interval()
   peer29.stop_interval()
   peer30.stop_interval()
   peer31.stop_interval()
   peer32.stop_interval()
   peer33.stop_interval()
   peer34.stop_interval()
   peer35.stop_interval()
   peer36.stop_interval()
   peer37.stop_interval()
   peer38.stop_interval()
   peer39.stop_interval()
   peer40.stop_interval()
   peer41.stop_interval()
   peer42.stop_interval()
   peer43.stop_interval()
   peer44.stop_interval()
   peer45.stop_interval()
   peer46.stop_interval()
   peer47.stop_interval()
   peer48.stop_interval()
   peer49.stop_interval()

   print peer0.get_chunks(timeout=5)
   print peer1.get_chunks(timeout=5)
   print peer2.get_chunks(timeout=5)
   print peer3.get_chunks(timeout=5)
   print peer4.get_chunks(timeout=5)
   print peer5.get_chunks(timeout=5)
   print peer6.get_chunks(timeout=5)
   print peer7.get_chunks(timeout=5)
   print peer8.get_chunks(timeout=5)
   print peer9.get_chunks(timeout=5)
   print peer10.get_chunks(timeout=5)
   print peer11.get_chunks(timeout=5)
   print peer12.get_chunks(timeout=5)
   print peer13.get_chunks(timeout=5)
   print peer14.get_chunks(timeout=5)
   print peer15.get_chunks(timeout=5)
   print peer16.get_chunks(timeout=5)
   print peer17.get_chunks(timeout=5)
   print peer18.get_chunks(timeout=5)
   print peer19.get_chunks(timeout=5)
   print peer20.get_chunks(timeout=5)
   print peer21.get_chunks(timeout=5)
   print peer22.get_chunks(timeout=5)
   print peer23.get_chunks(timeout=5)
   print peer24.get_chunks(timeout=5)
   print peer25.get_chunks(timeout=5)
   print peer26.get_chunks(timeout=5)
   print peer27.get_chunks(timeout=5)
   print peer28.get_chunks(timeout=5)
   print peer29.get_chunks(timeout=5)
   print peer30.get_chunks(timeout=5)
   print peer31.get_chunks(timeout=5)
   print peer32.get_chunks(timeout=5)
   print peer33.get_chunks(timeout=5)
   print peer34.get_chunks(timeout=5)
   print peer35.get_chunks(timeout=5)
   print peer36.get_chunks(timeout=5)
   print peer37.get_chunks(timeout=5)
   print peer38.get_chunks(timeout=5)
   print peer39.get_chunks(timeout=5)
   print peer40.get_chunks(timeout=5)
   print peer41.get_chunks(timeout=5)
   print peer42.get_chunks(timeout=5)
   print peer43.get_chunks(timeout=5)
   print peer44.get_chunks(timeout=5)
   print peer45.get_chunks(timeout=5)
   print peer46.get_chunks(timeout=5)
   print peer47.get_chunks(timeout=5)
   print peer48.get_chunks(timeout=5)
   print peer49.get_chunks(timeout=5)

   print peer0.get_values(timeout=5)
   print peer1.get_values(timeout=5)
   print peer2.get_values(timeout=5)
   print peer3.get_values(timeout=5)
   print peer4.get_values(timeout=5)
   print peer5.get_values(timeout=5)
   print peer6.get_values(timeout=5)
   print peer7.get_values(timeout=5)
   print peer8.get_values(timeout=5)
   print peer9.get_values(timeout=5)
   print peer10.get_values(timeout=5)
   print peer11.get_values(timeout=5)
   print peer12.get_values(timeout=5)
   print peer13.get_values(timeout=5)
   print peer14.get_values(timeout=5)
   print peer15.get_values(timeout=5)
   print peer16.get_values(timeout=5)
   print peer17.get_values(timeout=5)
   print peer18.get_values(timeout=5)
   print peer19.get_values(timeout=5)
   print peer20.get_values(timeout=5)
   print peer21.get_values(timeout=5)
   print peer22.get_values(timeout=5)
   print peer23.get_values(timeout=5)
   print peer24.get_values(timeout=5)
   print peer25.get_values(timeout=5)
   print peer26.get_values(timeout=5)
   print peer27.get_values(timeout=5)
   print peer28.get_values(timeout=5)
   print peer29.get_values(timeout=5)
   print peer30.get_values(timeout=5)
   print peer31.get_values(timeout=5)
   print peer32.get_values(timeout=5)
   print peer33.get_values(timeout=5)
   print peer34.get_values(timeout=5)
   print peer35.get_values(timeout=5)
   print peer36.get_values(timeout=5)
   print peer37.get_values(timeout=5)
   print peer38.get_values(timeout=5)
   print peer39.get_values(timeout=5)
   print peer40.get_values(timeout=5)
   print peer41.get_values(timeout=5)
   print peer42.get_values(timeout=5)
   print peer43.get_values(timeout=5)
   print peer44.get_values(timeout=5)
   print peer45.get_values(timeout=5)
   print peer46.get_values(timeout=5)
   print peer47.get_values(timeout=5)
   print peer48.get_values(timeout=5)
   print peer49.get_values(timeout=5)

   shutdown()